version: '4.17'
services:
  test-db:
    image: postgres:alpine3.17
    hostname: test-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123pswd
      POSTGRES_DB: getfitgo_test
  dev-db:
    image: postgres:alpine3.17
    hostname: dev-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123pswd
      POSTGRES_DB: getfitgo_dev

  
  
