export enum ContentType {
    User = 0,
    Club = 1,
    Message = 2,
    Attachment = 3,
    Chat = 4,
    Training = 5,
    Exercise = 6,
    Achievement = 7,
    Activity = 8,
    Calendar = 9,
    Calendar_entry = 10,
    Challenge = 11,
    Goal = 12,
    Reward = 13,
    Biometry = 14,
    Vatal = 15,
    Payment = 16,
    Discount = 17,
    Club_membership = 18,
}